server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin1234
    hikari:
      #最大連接數，默認是10
      maximum-pool-size: 30
      #最小空閒連接，默認10
      minimum-idle: 30
      #等待連接池分配連接的最大時長，超過該時長還沒有可用連接則發生超時異常
      connection-timeout: 5000
      #空閒連接的最大時長，空閒多久就被釋放回收，設置為0代表不讓回收
      idle-timeout: 0
      #一個連接的最大生命時間，超過該時間還沒使用就會被回收掉，最好不要超過8小時
      max-lifetime: 18000000

  #設置json返回時間的格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

